---
title: "Lecture 3"
subtitle: "Part 2"
output: github_document
---



# Visualization



```{r}
library(tidyverse)
library(patchwork)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## remember this plot?...

```{r}
weather_df %>% 
  ggplot(aes( x = tmin, y = tmax, color = name)) + geom_point(alpha = .4 )
```

labels

```{r}
weather_df %>% 
  ggplot(aes( x = tmin, y = tmax, color = name)) + geom_point(alpha = .4 ) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature",
    y = "MAximum daily temperature",
    caption = "Data from rnoaa package"
  )
```

## Scales

```{r}
weather_df %>% 
  ggplot(aes( x = tmin, y = tmax, color = name)) + geom_point(alpha = .4 ) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature",
    y = "MAximum daily temperature",
    caption = "Data from rnoaa package"
  ) + 
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0 C", "15 C")
  ) +
  scale_y_continuous(
    position = "right"
  )
```

look at color scales

```{r}
weather_df %>% 
  ggplot(aes( x = tmin, y = tmax, color = name)) + geom_point(alpha = .4 ) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature",
    y = "MAximum daily temperature",
    caption = "Data from rnoaa package"
  ) + scale_color_hue(name = "Location", h = c(50, 250))
```


```{r}
weather_df %>% 
  ggplot(aes( x = tmin, y = tmax, color = name)) + geom_point(alpha = .4 ) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature",
    y = "MAximum daily temperature",
    caption = "Data from rnoaa package"
  ) + viridis::scale_color_viridis(
    name = "Location", discrete = "TRUE"
  )
```

